In [1]:
import pandas as pd

In [2]:

reviews = pd.read_csv("archive/winemag-data_first150k.csv")

In [3]:
reviews

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...,...,...
150925,150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

In [11]:
group_by_review=reviews.groupby(["country"])
group_by_review

In [17]:
reviews.groupby(['country', 'province']).describe()

                           Unnamed: 0                                        \
                                count           mean           std      min
country   province
Albania   Mirditë                 2.0    4753.000000    156.977705   4642.0
Argentina Mendoza Province     4742.0   80158.115141  41984.529056     60.0
          Other                 889.0   84440.971879  41416.594319    455.0
Australia Australia Other       553.0   92211.954792  43849.886941   3822.0
          New South Wales       246.0   96444.069106  40438.869199   6457.0
...                               ...            ...           ...      ...
Uruguay   Juanico                19.0   95000.210526  40550.322345   3160.0
          Montevideo              3.0   12343.000000  13327.679355   3164.0
          Progreso                5.0    7712.200000    815.366605   6541.0
          San Jose               15.0   94775.933333  31770.395830  45423.0
          Uruguay                18.0  105691.388889  42003.844802   8978.0

                                                                     points  \
                                 25%       50%        75%       max   count
country   province
Albania   Mirditë            4697.50    4753.0    4808.50    4864.0     2.0
Argentina Mendoza Province  45282.25   83013.0  117217.25  149638.0  4742.0
          Other             53198.00   85813.0  119046.00  149628.0   889.0
Australia Australia Other   53699.00  100340.0  130288.00  150650.0   553.0
          New South Wales   63609.50  100699.5  138539.75  149548.0   246.0
...                              ...       ...        ...       ...     ...
Uruguay   Juanico           70160.00  103012.0  130880.00  143384.0    19.0
          Montevideo         4699.50    6235.0   16932.50   27630.0     3.0
          Progreso           7178.00    8133.0    8350.00    8359.0     5.0
          San Jose          70160.50  104733.0  119007.00  136418.0    15.0
          Uruguay           95225.50  125808.5  136722.75  137203.0    18.0

                                       ...               price             \
                                 mean  ...   75%   max   count       mean
country   province                     ...
Albania   Mirditë           88.000000  ...  88.0  88.0     2.0  20.000000
Argentina Mendoza Province  86.108182  ...  88.0  97.0  4706.0  20.858266
          Other             85.398200  ...  87.0  95.0   881.0  20.456300
Australia Australia Other   84.813743  ...  86.0  92.0   551.0  11.693285
          New South Wales   87.048780  ...  89.0  93.0   244.0  22.049180
...                               ...  ...   ...   ...     ...        ...
Uruguay   Juanico           84.894737  ...  86.0  90.0    12.0  29.333333
          Montevideo        89.333333  ...  89.5  90.0     3.0  40.333333
          Progreso          88.200000  ...  88.0  89.0     5.0  30.800000
          San Jose          84.333333  ...  84.0  89.0    15.0  26.400000
          Uruguay           83.611111  ...  86.0  89.0    18.0  20.388889


                                  std   min    25%   50%   75%    max
country   province
Albania   Mirditë            0.000000  20.0  20.00  20.0  20.0   20.0
Argentina Mendoza Province  19.819035   4.0  11.00  15.0  21.0  230.0
          Other             22.055162   5.0  11.00  14.0  20.0  250.0
Australia Australia Other    6.056877   5.0   8.00  10.0  13.0   65.0
          New South Wales   16.192186   8.0  13.00  17.0  26.0  125.0
...                               ...   ...    ...   ...   ...    ...
Uruguay   Juanico           18.031958   9.0  15.00  19.5  50.0   52.0
          Montevideo        16.041613  25.0  32.00  39.0  48.0   57.0
          Progreso          14.060583  17.0  22.00  23.0  46.0   46.0
          San Jose          17.463431  13.0  18.00  19.0  19.0   60.0
          Uruguay           10.342027  10.0  12.25  19.0  27.5   50.0

[455 rows x 24 columns]